# Netlify configuration file

[build]
  # Command to build the Next.js application
  command = "npm run build"
  # Directory where the built assets are located
  publish = ".next"

[dev]
  # Command to run the development server
  command = "npm run dev"
  port = 3000
  publish = ".next"

# This plugin is essential for correctly deploying Next.js sites on Netlify,
# as it handles server-side rendering, API routes, and other dynamic features.
[[plugins]]
  package = "@netlify/plugin-nextjs"